// AppDelegate.swift — generated by `react-native init` and patched to wire
// APNs callbacks into RNAstaPush. The base RN AppDelegate is preserved
// verbatim above the MARK; the additions live below.

import Foundation
import UIKit
import UserNotifications

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate {

  var window: UIWindow?
  var bridge: AnyObject?

  func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    UNUserNotificationCenter.current().delegate = self
    // RN bridge is set up by the generated portion of this file (omitted).
    return true
  }

  // MARK: APNs token forwarding to the RNAstaPush module

  func application(_ application: UIApplication,
                   didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    RNAstaPush.shared?.appDelegateDidRegister(deviceToken)
  }

  func application(_ application: UIApplication,
                   didFailToRegisterForRemoteNotificationsWithError error: Error) {
    NSLog("[PPLM] APNs registration failed: \(error.localizedDescription)")
  }

  // MARK: notification taps

  func userNotificationCenter(_ center: UNUserNotificationCenter,
                              didReceive response: UNNotificationResponse,
                              withCompletionHandler completionHandler: @escaping () -> Void) {
    let userInfo = response.notification.request.content.userInfo

    // Quick actions — Acknowledge / Escalate from the notification long-press.
    if response.actionIdentifier == "ACK" {
      if let eventId = userInfo["event_id"] as? String {
        RNAstaPush.shared?.acknowledgeFromNotification(eventId as NSString)
      }
      completionHandler(); return
    }
    if response.actionIdentifier == "ESCALATE" {
      // Forward as a tapped event with via=escalate so the JS app routes to the sheet.
      var enriched = userInfo
      enriched["via"] = "escalate"
      RNAstaPush.shared?.appDelegateDidReceive(enriched)
      completionHandler(); return
    }

    // Default action — body tap.
    RNAstaPush.shared?.appDelegateDidReceive(userInfo)
    completionHandler()
  }

  // MARK: foreground presentation — show banner even while the app is open
  func userNotificationCenter(_ center: UNUserNotificationCenter,
                              willPresent notification: UNNotification,
                              withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    if #available(iOS 14.0, *) {
      completionHandler([.banner, .sound, .list])
    } else {
      completionHandler([.alert, .sound])
    }
  }

  // MARK: notification categories — register Acknowledge / Escalate quick actions
  static func registerCategories() {
    let ack = UNNotificationAction(
      identifier: "ACK",
      title: "Acknowledge",
      options: [.authenticationRequired]
    )
    let escalate = UNNotificationAction(
      identifier: "ESCALATE",
      title: "Escalate",
      options: [.foreground, .destructive]
    )
    let category = UNNotificationCategory(
      identifier: "PPLM_ALERT",
      actions: [ack, escalate],
      intentIdentifiers: [],
      options: []
    )
    UNUserNotificationCenter.current().setNotificationCategories([category])
  }
}
